server:
  port: 8099
spring:
  application:
    name: gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: AUTH-SERVER
    crud:
      path: /micro-crud/**
      sensitive-headers:
      service-id: MICRO-CRUD
    cr:
      path: /micro-cr/**
      sensitive-headers:
      url: http://localhost:8081
    nodejs:
      path: /nodejs/**
      url: http://localhost:3000